# EDA

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

raw_data_dir = "../../raw_data/"

In [2]:
df_belchonok = pd.read_csv(raw_data_dir + "belchonok.csv")

df_future_9 = pd.read_csv(raw_data_dir + "FUTURE_9.csv")
df_future_10 = pd.read_csv(raw_data_dir + "FUTURE_10.csv")
df_future_11 = pd.read_csv(raw_data_dir + "FUTURE_11.csv")

df_granit_nauki = pd.read_csv(raw_data_dir + "granit_nauki.csv")

df_innopolis_1 = pd.read_csv(raw_data_dir + "innopolis_1.csv")
df_innopolis_2 = pd.read_csv(raw_data_dir + "innopolis_2.csv")
df_innopolis_3 = pd.read_csv(raw_data_dir + "innopolis_3.csv")

df_itmo = pd.read_csv(raw_data_dir + "itmo.csv")

df_MOSH = pd.read_csv(raw_data_dir + "MOSH.csv")

df_MOW_SCH_9 = pd.read_csv(raw_data_dir + "MOW_SCH_9.csv")
df_MOW_SCH_10 = pd.read_csv(raw_data_dir + "MOW_SCH_10.csv")
df_MOW_SCH_11 = pd.read_csv(raw_data_dir + "MOW_SCH_11.csv")

df_MOW_MUN_9 = pd.read_csv(raw_data_dir + "MOW_MUN_9.csv")
df_MOW_MUN_10 = pd.read_csv(raw_data_dir + "MOW_MUN_10.csv")
df_MOW_MUN_11 = pd.read_csv(raw_data_dir + "MOW_MUN_11.csv")

df_MOW_REG = pd.read_csv(raw_data_dir + "MOW_REG.csv")

df_reg_2026 = pd.read_csv(raw_data_dir + "reg_2026.csv")

df_vuz_akadem = pd.read_csv(raw_data_dir + "vuz_akadem.csv")

## Бельчонок

**Колонки:**
1. name - имя
2. total - баллы
3. result:
    - 0 - участник
    - 3 - пип

**Замечания:**
- есть один пропуск в баллах

In [3]:
df_belchonok.head()

            name  total  result
0  Хакимзянов И.     51       3
1  Хмелевский М.     48       3
2     Еникеев К.     45       3
3  Главатских В.     41       3
4    Савицкая Т.     40       3

In [4]:
df_belchonok['result'].value_counts()

result
1    170
3     98
2     95
Name: count, dtype: int64

In [5]:
df_belchonok.shape

(363, 3)

In [6]:
df_belchonok.isna().sum()

name      0
total     0
result    0
dtype: int64

---

## Шаг в будущее

**Колонки:**
1. surname - фамилия
2. name - имя
3. father_name - отчество
4. title:
    - 1 - призер
    - 2 - побед
5. (*grade*) - класс
6. (*place*) - место в зачете

**Предварительная обработка:**
1. Добавление колонок *grade*, *place*
2. Конкатинация

**Замечания**
- Один пропуск в отчестве

In [7]:
df_future_9.head()

      id      surname       name    father_name  title
0  65331      Альперт    Владияр      Андреевич      1
1  61520       Багров      Данил      Сергеевич      1
2  71206     Бацарова  Елизавета      Денисовна      1
3  48768  Белослудцев      Артём     Евгеньевич      1
4  63654    Замотохин       Глеб  Александрович      1

In [8]:
df_future_10.head()

      id    surname       name    father_name  title
0  68597     Анищук   Всеволод       Иванович      1
1  56287     Ботвин  Александр      Сергеевич      1
2  66747     Брылин     Михаил       Иванович      1
3  63730     Бубнов  Александр  Александрович      1
4  63548  Васильева      Мария        Юрьевна      1

In [9]:
df_future_11.head()

      id         surname       name    father_name  title
0  35616          Анохин       Глеб     Алексеевич      1
1  33114         Аргунов       Иван  Александрович      1
2  57954         Булахов  Владислав  Александрович      1
3  49991       Валиуллин    Альберт     Рустемович      1
4  91868  Волкова-Медова  Анастасия      Денисовна      1

In [10]:
df_future_9['title'].value_counts()

title
2    24
1    11
Name: count, dtype: int64

In [11]:
df_future_10['title'].value_counts()

title
2    31
1    15
Name: count, dtype: int64

In [12]:
df_future_11['title'].value_counts()

title
2    67
1    28
Name: count, dtype: int64

### Bit of preparing

In [13]:
df_future_9 = pd.read_csv(raw_data_dir + "FUTURE_9.csv").drop(columns=['id'])
df_future_10 = pd.read_csv(raw_data_dir + "FUTURE_10.csv").drop(columns=['id'])
df_future_11 = pd.read_csv(raw_data_dir + "FUTURE_11.csv").drop(columns=['id'])

df_future_9['grade'] = 9
df_future_10['grade'] = 10
df_future_11['grade'] = 11

df_future_9 = df_future_9.reset_index().rename(columns={'index': 'place'})
df_future_10 = df_future_10.reset_index().rename(columns={'index': 'place'})
df_future_11 = df_future_11.reset_index().rename(columns={'index': 'place'})

df_future = pd.concat([df_future_9, df_future_10, df_future_11])
df_future = df_future.sort_values(by=['grade', 'place'], ascending=[False, True])
df_future.head()

   place         surname       name    father_name  title  grade
0      0          Анохин       Глеб     Алексеевич      1     11
1      1         Аргунов       Иван  Александрович      1     11
2      2         Булахов  Владислав  Александрович      1     11
3      3       Валиуллин    Альберт     Рустемович      1     11
4      4  Волкова-Медова  Анастасия      Денисовна      1     11

In [14]:
df_future.isna().sum()

place          0
surname        0
name           0
father_name    1
title          0
grade          0
dtype: int64

---

## Гранит науки

**Колонки**
1. reg - регион
2. name - Фамилия И. О.
3. grade - класс
4. total - баллы
5. result:
    - 3 - пип 1 степень
    - 2 - пип 2 степень
    - 1 - пип 3 степень
    - 0 - участник

**Предварительная обработка**
1. Заполнение пропусков в имени на NO_NAME

**Замечания**
- колонка имя формата фамилия И. О.

In [15]:
df_granit_nauki.head()

                     reg           name grade total  result
0      Самарская область     Федотов М.    10  91,5       3
1     Московская область      Брылин М.    10    87       3
2    Воронежская область      Бубнов К.    10    78       2
3        Санкт-Петербург  Обиджанова А.    10    76       2
4  Новосибирская область     Лысаков Р.    10    76       2

In [16]:
df_granit_nauki['result'].value_counts()

result
0    603
1     85
2     31
3      7
Name: count, dtype: int64

In [17]:
df_granit_nauki.isna().sum()

reg       0
name      0
grade     0
total     0
result    0
dtype: int64

### Bit of preparing

In [18]:
df_granit_nauki['name'] = df_granit_nauki['name'].fillna("NO_NAME")

---

## Innopolis

**Колонки**
1. name - фамилия имя
2. reg - регион
3. total - баллы
4. grade - класс
5. (*stage*) - этап

**Предварительная обработка**
1. Добавление колонки *stage*
2. Конкатинация
3. Заполнение пропусков в именях на NO_NAME

**Замечание**
- есть пропуски в имени
- есть пропуски в регионе
- есть пропуски в классе

In [19]:
df_innopolis_1.head()

          name    A    B    C   D    E    F   result  grade
0   Коробко А.  100  100  100  85  100  485  Invited     11
1     Алоян Э.  100  100  100  76  100  476  Invited      9
2  Коновнин Л.  100  100  100  76  100  476  Invited     11
3  Халтурин А.  100  100  100  76  100  476  Invited     10
4  Карташов В.  100  100  100  49  100  449  Invited     10

In [20]:
df_innopolis_2.head()

             name    A    B    C   D    E    F   result  grade
0       Машира Д.  100  100  100  46  100  446  Invited     10
1   Правосудов Д.  100  100  100  80   39  419  Invited      9
2      Альмиев К.  100  100  100   .  100  400  Invited     11
3  Миннахметов И.  100   60  100  33  100  393  Invited     11
4      Звездин В.  100    0  100  80  100  380  Invited      9

In [21]:
df_innopolis_3.head()

            name    A    B    C    D    E   F  total  result  grade
0     Звездин В.  100  100  100  100  100  19    519     1.0     11
1      Кардаш К.  100  100  100  100  100  19    519     1.0     10
2   Кондрашин В.  100  100  100  100  100  19    519     1.0     10
3  Насыбуллин И.  100  100  100  100  100  19    519     1.0     10
4   Устименко А.  100  100  100  100  100  19    519     1.0     11

In [22]:
df_innopolis_1.isna().sum()

name        0
A           0
B           0
C           0
D           0
E           0
F           0
result    560
grade       0
dtype: int64

In [23]:
df_innopolis_2.isna().sum()

name        0
A           0
B           0
C           0
D           0
E           0
F           0
result    649
grade       0
dtype: int64

In [24]:
df_innopolis_3.isna().sum()

name        0
A           0
B           0
C           0
D           0
E           0
F           0
total       0
result    196
grade       0
dtype: int64

### Bit of preparing

In [25]:
df_innopolis_1 = pd.read_csv(raw_data_dir + "innopolis_1.csv")
df_innopolis_2 = pd.read_csv(raw_data_dir + "innopolis_2.csv")
df_innopolis_3 = pd.read_csv(raw_data_dir + "innopolis_3.csv")

df_innopolis_1['stage'] = 1
df_innopolis_2['stage'] = 2
df_innopolis_3['stage'] = 3

df_innopolis = pd.concat([df_innopolis_1, df_innopolis_2, df_innopolis_3])

df_innopolis['name'] = df_innopolis['name'].fillna("NO_NAME")
df_innopolis = df_innopolis.sort_values(['stage', 'grade', 'total'], ascending=[True, False, False])

df_innopolis.head()

               name    A    B    C   D  E    F   result  grade  stage  total
92   Abdulrahman A.  100  100  100  42  .  342  Invited     12      1    NaN
143        Adeeb O.  100  100  100   .  .  300  Invited     12      1    NaN
282         Judy W.  100    0   60  42  0  202      NaN     12      1    NaN
372        Laure H.  100   30    0  42  0  172      NaN     12      1    NaN
384    Abdalaziz M.  100   50   20   .  .  170      NaN     12      1    NaN

In [26]:
df_innopolis['grade'].value_counts()

grade
11    844
10    551
9     281
8     121
7      59
12     15
6       5
Name: count, dtype: int64

In [27]:
df_innopolis.isna().sum()

name         0
A            0
B            0
C            0
D            0
E            0
F            0
result    1405
grade        0
stage        0
total     1616
dtype: int64

---

## ITMO

**Колонки**
1. name - Фамилия Имя Отчество
2. reg - регион
3. result:
    - 3 - пип 1 степень
    - 2 - пип 2 степень
    - 1 - пип 3 степень

In [28]:
df_itmo.head()

            name                    reg  result  grade
0  Сисьмекова З.   Свердловская область       3      8
1       Щукин Н.                 Москва       3      8
2    Зеленкин К.                 Москва       3      8
3     Бисярин А.        Санкт-Петербург       2      8
4     Русанов Н.  Новосибирская область       2      8

In [29]:
df_itmo['result'].value_counts()

result
1    58
3    30
2    29
Name: count, dtype: int64

In [30]:
df_itmo.isna().sum()

name      0
reg       0
result    0
grade     0
dtype: int64

---

## MOSH

**Колонки**
1. surname - Фамилия
2. first_initial - первая буква имени
3. second_initial - первая буква отчества
4. class_study - класс
5. region - код региона
6. score - баллы
7. title:
    - победитель
    - призер2степени
    - призер3степени

In [31]:
df_MOSH.head()

,id,surname,first_inital,second_initial,class_study,class_partake,region,score,title
0,41376161,Островский,А,В,11,11,77,433.06,победитель
1,41376047,Ивлеев,М,С,10,11,77,371.52,победитель
2,41376080,Карпиков,Н,В,10,11,77,344.40,победитель
3,41376182,Горелов,Г,А,10,11,77,299.54,победитель
4,41376153,Девятов,С,А,10,11,77,283.99,победитель

In [32]:
df_MOSH['title'].value_counts()

title
призёр3степени    160
призёр2степени     91
победитель         79
Name: count, dtype: int64

In [33]:
df_MOSH.isna().sum()

id                0
surname           0
first_inital      0
second_initial    0
class_study       0
class_partake     0
region            0
score             0
title             0
dtype: int64

---

## ВСОШ: школьный этап | Москва

**Колонки**
1. surname - Фамилия
2. first_initial - Первая буква имени
3. second_initial - Первая буква отчества
4. class_partake - класс участия
5. class_study - класс обучекния
6. score - баллы
7. title:
    - победитель
    - призер
    - участник

**Предобработка**
1. Конкатенация

**Замечания**
1. Пропуски в букве отчества

In [34]:
df_MOW_SCH_9.head()

,id,surname,first_inital,second_initial,class_study,class_partake,region,score,title
0,325849054,Абубакиров,Д,Д,9,9,77,500.0,победитель
1,325849050,Богдановский,М,С,9,9,77,500.0,победитель
2,325832300,Горбачев,А,А,9,9,77,500.0,победитель
3,325847084,Дамбаев,Д,Ж,9,9,77,500.0,победитель
4,325850582,Дементьев,Г,А,9,9,77,500.0,победитель

In [35]:
df_MOW_MUN_10.head()

,id,surname,first_inital,second_initial,class_study,class_partake,region,score,title
0,41197363,Артемьев,М,М,10,10,77,500.0,победитель
1,41196929,Васильев,О,И,10,10,77,500.0,победитель
2,41197075,Волынец,П,Р,10,10,77,500.0,победитель
3,41197141,Вяргизова,А,Д,10,10,77,500.0,победитель
4,41197220,Горелов,Г,А,10,10,77,500.0,победитель

In [36]:
df_MOW_SCH_11.head()

,id,surname,first_inital,second_initial,class_study,class_partake,region,score,title
0,325828830,Александров,Н,А,11,11,77,500.0,победитель
1,325848986,Аргунов,И,А,11,11,77,500.0,победитель
2,325826133,Артюхов,И,С,11,11,77,500.0,победитель
3,325826406,Бейлезон,К,А,11,11,77,500.0,победитель
4,325845538,Бичоева,А,А,11,11,77,500.0,победитель

In [37]:
df_MOW_MUN_10.head()

,id,surname,first_inital,second_initial,class_study,class_partake,region,score,title
0,41197363,Артемьев,М,М,10,10,77,500.0,победитель
1,41196929,Васильев,О,И,10,10,77,500.0,победитель
2,41197075,Волынец,П,Р,10,10,77,500.0,победитель
3,41197141,Вяргизова,А,Д,10,10,77,500.0,победитель
4,41197220,Горелов,Г,А,10,10,77,500.0,победитель

In [38]:
df_MOW_MUN_10['title'].value_counts()

title
участник      672
призер        193
победитель     66
Name: count, dtype: int64

### Bit of preparing

In [39]:
df_MOW_SCH_9 = pd.read_csv(raw_data_dir + "MOW_SCH_9.csv")
df_MOW_SCH_10 = pd.read_csv(raw_data_dir + "MOW_SCH_10.csv")
df_MOW_SCH_11 = pd.read_csv(raw_data_dir + "MOW_SCH_11.csv")

df_MOW_SCH = pd.concat([df_MOW_SCH_9, df_MOW_SCH_10, df_MOW_SCH_11])
df_MOW_SCH.head()

,id,surname,first_inital,second_initial,class_study,class_partake,region,score,title
0,325849054,Абубакиров,Д,Д,9,9,77,500.0,победитель
1,325849050,Богдановский,М,С,9,9,77,500.0,победитель
2,325832300,Горбачев,А,А,9,9,77,500.0,победитель
3,325847084,Дамбаев,Д,Ж,9,9,77,500.0,победитель
4,325850582,Дементьев,Г,А,9,9,77,500.0,победитель

In [40]:
df_MOW_SCH.isna().sum()

id                  0
surname             0
first_inital        0
second_initial    148
class_study         0
class_partake       0
region              0
score               0
title               0
dtype: int64

---

## ВСОШ: муниципальный этап | Москва

**Колонки**
1. surname - Фамилия
2. first_initial - Первая буква имени
3. second_initial - Первая буква отчества
4. class_partake - класс участия
5. class_study - класс обучекния
6. score - баллы
7. title:
    - победитель
    - призер
    - участник

**Предобработка**
1. Конкатенация

**Замечания**
1. Пропуски в букве отчества

In [41]:
df_MOW_MUN_9.head()

,id,surname,first_inital,second_initial,class_study,class_partake,region,score,title
0,41196750,Богдановский,М,С,9,9,77,500.0,победитель
1,41195931,Гасаненко,А,А,9,9,77,500.0,победитель
2,41195776,Давыдов,П,Д,9,9,77,500.0,победитель
3,41195582,Дементьев,Г,А,9,9,77,500.0,победитель
4,41195713,Дьяконов,К,А,9,9,77,500.0,победитель

In [42]:
df_MOW_MUN_10.head()

,id,surname,first_inital,second_initial,class_study,class_partake,region,score,title
0,41197363,Артемьев,М,М,10,10,77,500.0,победитель
1,41196929,Васильев,О,И,10,10,77,500.0,победитель
2,41197075,Волынец,П,Р,10,10,77,500.0,победитель
3,41197141,Вяргизова,А,Д,10,10,77,500.0,победитель
4,41197220,Горелов,Г,А,10,10,77,500.0,победитель

In [43]:
df_MOW_MUN_11.head()

,id,surname,first_inital,second_initial,class_study,class_partake,region,score,title
0,41197798,Венгеров,В,Р,11,11,77,500.0,победитель
1,41197900,Голубов,Н,М,11,11,77,500.0,победитель
2,41197975,Иванов,П,И,11,11,77,500.0,победитель
3,41197971,Игнатов,Д,М,11,11,77,500.0,победитель
4,41197711,Касинов,В,С,11,11,77,500.0,победитель

### Bit of preparing

In [44]:
df_MOW_MUN_9 = pd.read_csv(raw_data_dir + "MOW_MUN_9.csv")
df_MOW_MUN_10 = pd.read_csv(raw_data_dir + "MOW_MUN_10.csv")
df_MOW_MUN_11 = pd.read_csv(raw_data_dir + "MOW_MUN_11.csv")

df_MOW_MUN = pd.concat([df_MOW_MUN_9, df_MOW_MUN_10, df_MOW_MUN_11])
df_MOW_MUN.head()

,id,surname,first_inital,second_initial,class_study,class_partake,region,score,title
0,41196750,Богдановский,М,С,9,9,77,500.0,победитель
1,41195931,Гасаненко,А,А,9,9,77,500.0,победитель
2,41195776,Давыдов,П,Д,9,9,77,500.0,победитель
3,41195582,Дементьев,Г,А,9,9,77,500.0,победитель
4,41195713,Дьяконов,К,А,9,9,77,500.0,победитель

In [45]:
df_MOW_MUN.isna().sum()

id                 0
surname            0
first_inital       0
second_initial    12
class_study        0
class_partake      0
region             0
score              0
title              0
dtype: int64

---

## ВСОШ: региональный этап | Москва

**Колонки**
1. surname - Фамилия
2. first_initial - Первая буква имени
3. second_initial - Первая буква отчества
4. class_partake - класс участия
5. class_study - класс обучекния
6. score - баллы
7. title:
    - победитель
    - призер
    - участник

**Замечания**
1. Пропуски в букве отчества
2. Пропуски в баллах

In [46]:
df_MOW_REG.head()

,id,surname,first_inital,second_initial,class_study,class_partake,region,score,title
0,41232839,Артюхов,И,С,11,11,77,NaN,победитель
1,41232893,Васильев,А,А,11,11,77,NaN,победитель
2,41232735,Данилов,Н,И,11,11,77,NaN,победитель
3,41232902,Дьяконов,С,А,11,11,77,NaN,победитель
4,41232856,Жиганов,В,А,11,11,77,NaN,победитель

In [47]:
df_MOW_REG.isna().sum()

id                  0
surname             0
first_inital        0
second_initial      3
class_study         0
class_partake       0
region              0
score             915
title               0
dtype: int64

---

## ВСОШ: региональный этап | Все

**Колонки**
1. Имя => name
2. Регион => region
3. Класс => grade
4. A1
5. B1
6. C1
7. D1
8. A2
9. B2
10. C2
11. D2
12. Sum

**Предварительная обработка**
1. Переименование колонок

**Замечания**
- пропуски в баллах по задачам

In [48]:
df_reg_2026.head()

,Имя,Регион,Класс,A1,B1,C1,D1,A2,B2,C2,D2,Sum
0,Ашахмуров Артур Васильевич,Московская область,10,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0
1,Гриненко Артемий Андреевич,Москва,10,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0
2,Звездин Владимир Сергеевич,Санкт-Петербург,11,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0
3,Кравченко Максим Юрьевич,Москва,10,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0
4,Кузнецов Иван Александрович,Санкт-Петербург,11,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0

### Bit of preparing

In [49]:
df_reg_2026 = df_reg_2026.rename(columns={'Имя': 'name', 'Регион': 'region', 'Класс': 'grade'})

df_reg_2026.head()

,name,region,grade,A1,B1,C1,D1,A2,B2,C2,D2,Sum
0,Ашахмуров Артур Васильевич,Московская область,10,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0
1,Гриненко Артемий Андреевич,Москва,10,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0
2,Звездин Владимир Сергеевич,Санкт-Петербург,11,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0
3,Кравченко Максим Юрьевич,Москва,10,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0
4,Кузнецов Иван Александрович,Санкт-Петербург,11,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0

In [50]:
df_reg_2026.isna().sum()

name         0
region       0
grade        0
A1         525
B1        1541
C1        2681
D1        3229
A2         705
B2        1544
C2        1829
D2        4284
Sum          0
dtype: int64

---

## Вузовская академическая олимпиада

**Колонки**
1. name - фамилия имя отчество
2. reg - регион
3. total - баллы
4. grade - класс

In [51]:
df_vuz_akadem.head()

            name                   reg  total  grade
0  Мухамадиев Д.  Республика Татарстан    604     10
1   Котлечков Е.  Свердловская область    594     11
2     Андреев А.    Ростовская область    585     11
3     Лободов М.         Пермский край    570     10
4   Кондрашин В.  Свердловская область    548     10

In [52]:
df_vuz_akadem.isna().sum()

name     0
reg      0
total    0
grade    0
dtype: int64

---