# EDA

In [129]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

raw_data_dir = "../../raw_data/"

In [169]:
df_belchonok = pd.read_csv(raw_data_dir + "belchonok.csv")

df_future_9 = pd.read_csv(raw_data_dir + "FUTURE_9.csv")
df_future_10 = pd.read_csv(raw_data_dir + "FUTURE_10.csv")
df_future_11 = pd.read_csv(raw_data_dir + "FUTURE_11.csv")

df_granit_nauki = pd.read_csv(raw_data_dir + "granit_nauki.csv")

df_innopolis_1 = pd.read_csv(raw_data_dir + "innopolis_1.csv")
df_innopolis_2 = pd.read_csv(raw_data_dir + "innopolis_2.csv")
df_innopolis_3 = pd.read_csv(raw_data_dir + "innopolis_3.csv")

df_itmo = pd.read_csv(raw_data_dir + "itmo.csv")

df_MOSH = pd.read_csv(raw_data_dir + "MOSH.csv")

df_MOW_SCH_9 = pd.read_csv(raw_data_dir + "MOW_SCH_9.csv")
df_MOW_SCH_10 = pd.read_csv(raw_data_dir + "MOW_SCH_10.csv")
df_MOW_SCH_11 = pd.read_csv(raw_data_dir + "MOW_SCH_11.csv")

df_MOW_MUN_9 = pd.read_csv(raw_data_dir + "MOW_MUN_9.csv")
df_MOW_MUN_10 = pd.read_csv(raw_data_dir + "MOW_MUN_10.csv")
df_MOW_MUN_11 = pd.read_csv(raw_data_dir + "MOW_MUN_11.csv")

df_MOW_REG = pd.read_csv(raw_data_dir + "MOW_REG.csv")

df_reg_2026 = pd.read_csv(raw_data_dir + "reg_2026.csv")

df_vuz_akadem = pd.read_csv(raw_data_dir + "vuz_akadem.csv")

## Бельчонок

**Колонки:**
1. name - имя
2. total - баллы
3. result:
    - 0 - участник
    - 3 - пип

**Замечания:**
- есть один пропуск в баллах

In [131]:
df_belchonok.head()

                           name  total  result
0  Хакимзянов Ильдар Марселевич   51.0       3
1  Хмелевский Максим Михайлович   48.0       3
2      Еникеев Кирилл Денисович   45.0       3
3   Главатских Виолика Игоревна   41.0       3
4  Савицкая Таисия Владимировна   40.0       3

In [132]:
df_belchonok['result'].value_counts()

result
1    170
3     98
2     95
0      1
Name: count, dtype: int64

In [133]:
df_belchonok.shape

(364, 3)

In [134]:
df_belchonok.isna().sum()

name      0
total     1
result    0
dtype: int64

---

## Шаг в будущее

**Колонки:**
1. surname - фамилия
2. name - имя
3. father_name - отчество
4. title:
    - 1 - призер
    - 2 - побед
5. (*grade*) - класс
6. (*place*) - место в зачете

**Предварительная обработка:**
1. Добавление колонок *grade*, *place*
2. Конкатинация

**Замечания**
- Один пропуск в отчестве

In [135]:
df_future_9.head()

      id      surname       name    father_name  title
0  65331      Альперт    Владияр      Андреевич      1
1  61520       Багров      Данил      Сергеевич      1
2  71206     Бацарова  Елизавета      Денисовна      1
3  48768  Белослудцев      Артём     Евгеньевич      1
4  63654    Замотохин       Глеб  Александрович      1

In [136]:
df_future_10.head()

      id    surname       name    father_name  title
0  68597     Анищук   Всеволод       Иванович      1
1  56287     Ботвин  Александр      Сергеевич      1
2  66747     Брылин     Михаил       Иванович      1
3  63730     Бубнов  Александр  Александрович      1
4  63548  Васильева      Мария        Юрьевна      1

In [137]:
df_future_11.head()

      id         surname       name    father_name  title
0  35616          Анохин       Глеб     Алексеевич      1
1  33114         Аргунов       Иван  Александрович      1
2  57954         Булахов  Владислав  Александрович      1
3  49991       Валиуллин    Альберт     Рустемович      1
4  91868  Волкова-Медова  Анастасия      Денисовна      1

In [138]:
df_future_9['title'].value_counts()

title
2    24
1    11
Name: count, dtype: int64

In [139]:
df_future_10['title'].value_counts()

title
2    31
1    15
Name: count, dtype: int64

In [140]:
df_future_11['title'].value_counts()

title
2    67
1    28
Name: count, dtype: int64

### Bit of preparing

In [141]:
df_future_9 = pd.read_csv(raw_data_dir + "FUTURE_9.csv").drop(columns=['id'])
df_future_10 = pd.read_csv(raw_data_dir + "FUTURE_10.csv").drop(columns=['id'])
df_future_11 = pd.read_csv(raw_data_dir + "FUTURE_11.csv").drop(columns=['id'])

df_future_9['grade'] = 9
df_future_10['grade'] = 10
df_future_11['grade'] = 11

df_future_9 = df_future_9.reset_index().rename(columns={'index': 'place'})
df_future_10 = df_future_10.reset_index().rename(columns={'index': 'place'})
df_future_11 = df_future_11.reset_index().rename(columns={'index': 'place'})

df_future = pd.concat([df_future_9, df_future_10, df_future_11])
df_future = df_future.sort_values(by=['grade', 'place'], ascending=[False, True])
df_future.head()

   place         surname       name    father_name  title  grade
0      0          Анохин       Глеб     Алексеевич      1     11
1      1         Аргунов       Иван  Александрович      1     11
2      2         Булахов  Владислав  Александрович      1     11
3      3       Валиуллин    Альберт     Рустемович      1     11
4      4  Волкова-Медова  Анастасия      Денисовна      1     11

In [142]:
df_future.isna().sum()

place          0
surname        0
name           0
father_name    1
title          0
grade          0
dtype: int64

---

## Гранит науки

**Колонки**
1. reg - регион
2. name - Фамилия И. О.
3. grade - класс
4. total - баллы
5. result:
    - 3 - пип 1 степень
    - 2 - пип 2 степень
    - 1 - пип 3 степень
    - 0 - участник

**Предварительная обработка**
1. Заполнение пропусков в имени на NO_NAME

**Замечания**
- колонка имя формата фамилия И. О.

In [148]:
df_granit_nauki.head()

                     reg              name grade total  result
0      Самарская область     Федотов М. С.    10  91,5       3
1     Московская область      Брылин М. И.    10    87       3
2    Воронежская область      Бубнов К. С.    10    78       2
3        Санкт-Петербург  Обиджанова А. С.    10    76       2
4  Новосибирская область     Лысаков Р. К.    10    76       2

In [149]:
df_granit_nauki['result'].value_counts()

result
0    603
1     85
2     31
3      7
Name: count, dtype: int64

In [150]:
df_granit_nauki.isna().sum()

reg       0
name      0
grade     0
total     0
result    0
dtype: int64

### Bit of preparing

In [151]:
df_granit_nauki['name'] = df_granit_nauki['name'].fillna("NO_NAME")

---

## Innopolis

**Колонки**
1. name - фамилия имя
2. reg - регион
3. total - баллы
4. grade - класс
5. (*stage*) - этап

**Предварительная обработка**
1. Добавление колонки *stage*
2. Конкатинация
3. Заполнение пропусков в именях на NO_NAME

**Замечание**
- есть пропуски в имени
- есть пропуски в регионе
- есть пропуски в классе

In [152]:
df_innopolis_1.head()

                 name                      reg  total  grade
0      Коробко Андрей      Республика Беларусь    485   11.0
1         Алоян Эдгар                      NaN    476    NaN
2        Коновнин Лев                г. Москва    476   11.0
3     Халтурин Андрей  Калининградская область    476   10.0
4  Карташов Владислав                г. Москва    449   10.0

In [153]:
df_innopolis_2.head()

                   name                               reg  total  grade
0         Машира Даниил              Республика Казахстан    446   10.0
1     Правосудов Даниил                 Самарская область    419    9.0
2         Альмиев Карим  Республика Татарстан (Татарстан)    400   11.0
3  Миннахметов Искандер  Республика Татарстан (Татарстан)    393   11.0
4      Звездин Владимир               Челябинская область    380    9.0

In [154]:
df_innopolis_3.head()

                         name                               reg  total  grade
0  Звездин Владимир Сергеевич                   Санкт-Петербург    519   11.0
1      Кардаш Кирилл Олегович               Республика Беларусь    519   10.0
2  Кондрашин Всеволод Юрьевич              Свердловская область    519   10.0
3  Насыбуллин Ильяс Ринатович  Республика Татарстан (Татарстан)    519   10.0
4  Устименко Артём Витальевич                         г. Москва    519   11.0

In [155]:
df_innopolis_1.isna().sum()

name      3
reg      70
total     0
grade    28
dtype: int64

In [156]:
df_innopolis_2.isna().sum()

name      1
reg      39
total     0
grade    10
dtype: int64

In [157]:
df_innopolis_3.isna().sum()

name     0
reg      0
total    0
grade    2
dtype: int64

### Bit of preparing

In [158]:
df_innopolis_1 = pd.read_csv(raw_data_dir + "innopolis_1.csv")
df_innopolis_2 = pd.read_csv(raw_data_dir + "innopolis_2.csv")
df_innopolis_3 = pd.read_csv(raw_data_dir + "innopolis_3.csv")

df_innopolis_1['stage'] = 1
df_innopolis_2['stage'] = 2
df_innopolis_3['stage'] = 3

df_innopolis = pd.concat([df_innopolis_1, df_innopolis_2, df_innopolis_3])

df_innopolis['name'] = df_innopolis['name'].fillna("NO_NAME")
df_innopolis = df_innopolis.sort_values(['stage', 'grade', 'total'], ascending=[True, False, False])

df_innopolis.head()

                   name                            reg  total  grade  stage
92   Abdulrahman Ahdali  Сирийская Арабская Республика    342   12.0      1
143         Adeeb Obedo  Сирийская Арабская Республика    300   12.0      1
282          Judy Wafai  Сирийская Арабская Республика    202   12.0      1
372         Laure Hadad  Сирийская Арабская Республика    172   12.0      1
384     Abdalaziz Marie  Сирийская Арабская Республика    170   12.0      1

In [159]:
df_innopolis['grade'].value_counts()

grade
11.0    794
10.0    518
9.0     264
8.0     112
1.0      76
7.0      52
12.0     15
6.0       5
Name: count, dtype: int64

In [160]:
df_innopolis.isna().sum()

name       0
reg      109
total      0
grade     40
stage      0
dtype: int64

---

## ITMO

**Колонки**
1. name - Фамилия Имя Отчество
2. reg - регион
3. result:
    - 3 - пип 1 степень
    - 2 - пип 2 степень
    - 1 - пип 3 степень

In [161]:
df_itmo.head()

                         name                    reg  result  grade
0  Сисьмекова Злата Артемовна   Свердловская область       3      8
1  Щукин Никита Александрович                 Москва       3      8
2  Зеленкин Кирилл Викторович                 Москва       3      8
3   Бисярин Андрей Евгеньевич        Санкт-Петербург       2      8
4  Русанов Николай Алексеевич  Новосибирская область       2      8

In [162]:
df_itmo['result'].value_counts()

result
1    58
3    30
2    29
Name: count, dtype: int64

In [163]:
df_itmo.isna().sum()

name      0
reg       0
result    0
grade     0
dtype: int64

---

## MOSH

**Колонки**
1. surname - Фамилия
2. first_initial - первая буква имени
3. second_initial - первая буква отчества
4. class_study - класс
5. region - код региона
6. score - баллы
7. title:
    - победитель
    - призер2степени
    - призер3степени

In [164]:
df_MOSH.head()

,id,surname,first_inital,second_initial,class_partake,class_study,region,score,title
0,41376161,Островский,А,В,11,11,77,433.06,победитель
1,41376047,Ивлеев,М,С,11,10,77,371.52,победитель
2,41376080,Карпиков,Н,В,11,10,77,344.40,победитель
3,41376182,Горелов,Г,А,11,10,77,299.54,победитель
4,41376153,Девятов,С,А,11,10,77,283.99,победитель

In [166]:
df_MOSH['title'].value_counts()

title
призёр3степени    160
призёр2степени     91
победитель         79
Name: count, dtype: int64

In [168]:
df_MOSH.isna().sum()

id                0
surname           0
first_inital      0
second_initial    0
class_partake     0
class_study       0
region            0
score             0
title             0
dtype: int64

---

## ВСОШ: школьный этап | Москва

**Колонки**
1. surname - Фамилия
2. first_initial - Первая буква имени
3. second_initial - Первая буква отчества
4. class_partake - класс участия
5. class_study - класс обучекния
6. score - баллы
7. title:
    - победитель
    - призер
    - участник

**Предобработка**
1. Конкатенация

**Замечания**
1. Пропуски в букве отчества

In [170]:
df_MOW_SCH_9.head()

,id,surname,first_inital,second_initial,class_partake,class_study,region,score,title
0,325849054,Абубакиров,Д,Д,9,9,77,500.0,победитель
1,325849050,Богдановский,М,С,9,9,77,500.0,победитель
2,325832300,Горбачев,А,А,9,9,77,500.0,победитель
3,325847084,Дамбаев,Д,Ж,9,9,77,500.0,победитель
4,325850582,Дементьев,Г,А,9,9,77,500.0,победитель

In [171]:
df_MOW_MUN_10.head()

,id,surname,first_inital,second_initial,class_partake,class_study,region,score,title
0,41197363,Артемьев,М,М,10,10,77,500.0,победитель
1,41196929,Васильев,О,И,10,10,77,500.0,победитель
2,41197075,Волынец,П,Р,10,10,77,500.0,победитель
3,41197141,Вяргизова,А,Д,10,10,77,500.0,победитель
4,41197220,Горелов,Г,А,10,10,77,500.0,победитель

In [173]:
df_MOW_SCH_11.head()

,id,surname,first_inital,second_initial,class_partake,class_study,region,score,title
0,325828830,Александров,Н,А,11,11,77,500.0,победитель
1,325848986,Аргунов,И,А,11,11,77,500.0,победитель
2,325826133,Артюхов,И,С,11,11,77,500.0,победитель
3,325826406,Бейлезон,К,А,11,11,77,500.0,победитель
4,325845538,Бичоева,А,А,11,11,77,500.0,победитель

In [174]:
df_MOW_MUN_10.head()

,id,surname,first_inital,second_initial,class_partake,class_study,region,score,title
0,41197363,Артемьев,М,М,10,10,77,500.0,победитель
1,41196929,Васильев,О,И,10,10,77,500.0,победитель
2,41197075,Волынец,П,Р,10,10,77,500.0,победитель
3,41197141,Вяргизова,А,Д,10,10,77,500.0,победитель
4,41197220,Горелов,Г,А,10,10,77,500.0,победитель

In [175]:
df_MOW_MUN_10['title'].value_counts()

title
участник      672
призер        193
победитель     66
Name: count, dtype: int64

### Bit of preparing

In [177]:
df_MOW_SCH_9 = pd.read_csv(raw_data_dir + "MOW_SCH_9.csv")
df_MOW_SCH_10 = pd.read_csv(raw_data_dir + "MOW_SCH_10.csv")
df_MOW_SCH_11 = pd.read_csv(raw_data_dir + "MOW_SCH_11.csv")

df_MOW_SCH = pd.concat([df_MOW_SCH_9, df_MOW_SCH_10, df_MOW_SCH_11])
df_MOW_SCH.head()

,id,surname,first_inital,second_initial,class_partake,class_study,region,score,title
0,325849054,Абубакиров,Д,Д,9,9,77,500.0,победитель
1,325849050,Богдановский,М,С,9,9,77,500.0,победитель
2,325832300,Горбачев,А,А,9,9,77,500.0,победитель
3,325847084,Дамбаев,Д,Ж,9,9,77,500.0,победитель
4,325850582,Дементьев,Г,А,9,9,77,500.0,победитель

In [178]:
df_MOW_SCH.isna().sum()

id                  0
surname             0
first_inital        0
second_initial    148
class_partake       0
class_study         0
region              0
score               0
title               0
dtype: int64

---

## ВСОШ: муниципальный этап | Москва

**Колонки**
1. surname - Фамилия
2. first_initial - Первая буква имени
3. second_initial - Первая буква отчества
4. class_partake - класс участия
5. class_study - класс обучекния
6. score - баллы
7. title:
    - победитель
    - призер
    - участник

**Предобработка**
1. Конкатенация

**Замечания**
1. Пропуски в букве отчества

In [182]:
df_MOW_MUN_9.head()

,id,surname,first_inital,second_initial,class_partake,class_study,region,score,title
0,41196750,Богдановский,М,С,9,9,77,500.0,победитель
1,41195931,Гасаненко,А,А,9,9,77,500.0,победитель
2,41195776,Давыдов,П,Д,9,9,77,500.0,победитель
3,41195582,Дементьев,Г,А,9,9,77,500.0,победитель
4,41195713,Дьяконов,К,А,9,9,77,500.0,победитель

In [183]:
df_MOW_MUN_10.head()

,id,surname,first_inital,second_initial,class_partake,class_study,region,score,title
0,41197363,Артемьев,М,М,10,10,77,500.0,победитель
1,41196929,Васильев,О,И,10,10,77,500.0,победитель
2,41197075,Волынец,П,Р,10,10,77,500.0,победитель
3,41197141,Вяргизова,А,Д,10,10,77,500.0,победитель
4,41197220,Горелов,Г,А,10,10,77,500.0,победитель

In [184]:
df_MOW_MUN_11.head()

,id,surname,first_inital,second_initial,class_partake,class_study,region,score,title
0,41197798,Венгеров,В,Р,11,11,77,500.0,победитель
1,41197900,Голубов,Н,М,11,11,77,500.0,победитель
2,41197975,Иванов,П,И,11,11,77,500.0,победитель
3,41197971,Игнатов,Д,М,11,11,77,500.0,победитель
4,41197711,Касинов,В,С,11,11,77,500.0,победитель

### Bit of preparing

In [185]:
df_MOW_MUN_9 = pd.read_csv(raw_data_dir + "MOW_MUN_9.csv")
df_MOW_MUN_10 = pd.read_csv(raw_data_dir + "MOW_MUN_10.csv")
df_MOW_MUN_11 = pd.read_csv(raw_data_dir + "MOW_MUN_11.csv")

df_MOW_MUN = pd.concat([df_MOW_MUN_9, df_MOW_MUN_10, df_MOW_MUN_11])
df_MOW_MUN.head()

,id,surname,first_inital,second_initial,class_partake,class_study,region,score,title
0,41196750,Богдановский,М,С,9,9,77,500.0,победитель
1,41195931,Гасаненко,А,А,9,9,77,500.0,победитель
2,41195776,Давыдов,П,Д,9,9,77,500.0,победитель
3,41195582,Дементьев,Г,А,9,9,77,500.0,победитель
4,41195713,Дьяконов,К,А,9,9,77,500.0,победитель

In [186]:
df_MOW_MUN.isna().sum()

id                 0
surname            0
first_inital       0
second_initial    12
class_partake      0
class_study        0
region             0
score              0
title              0
dtype: int64

---