# EDA

In [591]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [592]:
raw_data_dir = "../../raw_data/"
preprocessed_data_dir = "./preprocessed_data/"
year2425_dir = "24-25/"
year2526_dir = "25-26/"

belchonok_dir = "belchonok/"
belchonok_filename = "belchonok.csv"

df_belchonok2425 = pd.read_csv(raw_data_dir + belchonok_dir + year2425_dir + belchonok_filename)
df_belchonok2526 = pd.read_csv(raw_data_dir + belchonok_dir + year2526_dir + belchonok_filename)

future_dir = "StepInFuture/"
future_filename = "FUTURE"

df_future2526_9 = pd.read_csv(raw_data_dir + future_dir + year2526_dir + future_filename + "_9.csv")
df_future2526_10 = pd.read_csv(raw_data_dir + future_dir + year2526_dir + future_filename + "_10.csv")
df_future2526_11 = pd.read_csv(raw_data_dir + future_dir + year2526_dir + future_filename + "_11.csv")

granit_dir = "GranitNauki/"
granit_filename = "granit_nauki.csv"

df_granit_nauki2526 = pd.read_csv(raw_data_dir + granit_dir + year2526_dir + granit_filename)

innopolis_dir = "Innopolis/"
innopolis_filename = "innopolis"

df_innopolis2425_1 = pd.read_csv(raw_data_dir + innopolis_dir + year2425_dir + innopolis_filename + "_1.csv")
df_innopolis2425_2 = pd.read_csv(raw_data_dir + innopolis_dir + year2425_dir + innopolis_filename + "_2.csv")
df_innopolis2425_3 = pd.read_csv(raw_data_dir + innopolis_dir + year2425_dir + innopolis_filename + "_3.csv")

df_innopolis2526_1 = pd.read_csv(raw_data_dir + innopolis_dir + year2526_dir + innopolis_filename + "_1.csv")
df_innopolis2526_2 = pd.read_csv(raw_data_dir + innopolis_dir + year2526_dir + innopolis_filename + "_2.csv")
df_innopolis2526_3 = pd.read_csv(raw_data_dir + innopolis_dir + year2526_dir + innopolis_filename + "_3.csv")

itmo_dir = "ITMO/"
itmo_filename = "itmo.csv"

df_itmo2425 = pd.read_csv(raw_data_dir + itmo_dir + year2425_dir + itmo_filename)

df_itmo2526 = pd.read_csv(raw_data_dir + itmo_dir + year2526_dir + itmo_filename)

mosh_dir = "MOSH/"
mosh_filename = "MOSH.csv"

df_MOSH2526 = pd.read_csv(raw_data_dir + mosh_dir + year2526_dir + mosh_filename)

open_dir = "OpenStudentOlympiad/"
open_filename = "open.csv"

df_open2425 = pd.read_csv(raw_data_dir + open_dir + year2425_dir + open_filename)

df_open2526 = pd.read_csv(raw_data_dir + open_dir + year2526_dir + open_filename)

ARSO_dir = "ARSO/"
MOW_SCH_filename = "MOW_SCH"

df_MOW_SCH2425_9 = pd.read_csv(raw_data_dir + ARSO_dir + year2425_dir + MOW_SCH_filename + "_9.csv")
df_MOW_SCH2425_10 = pd.read_csv(raw_data_dir + ARSO_dir + year2425_dir + MOW_SCH_filename + "_10.csv")
df_MOW_SCH2425_11 = pd.read_csv(raw_data_dir + ARSO_dir + year2425_dir + MOW_SCH_filename + "_11.csv")

df_MOW_SCH2526_9 = pd.read_csv(raw_data_dir + ARSO_dir + year2526_dir + MOW_SCH_filename + "_9.csv")
df_MOW_SCH2526_10 = pd.read_csv(raw_data_dir + ARSO_dir + year2526_dir + MOW_SCH_filename + "_10.csv")
df_MOW_SCH2526_11 = pd.read_csv(raw_data_dir + ARSO_dir + year2526_dir + MOW_SCH_filename + "_11.csv")

MOW_MUN_filename = "MOW_MUN"

df_MOW_MUN2425_9 = pd.read_csv(raw_data_dir + ARSO_dir + year2425_dir + MOW_MUN_filename + "_9.csv")
df_MOW_MUN2425_10 = pd.read_csv(raw_data_dir + ARSO_dir + year2425_dir + MOW_MUN_filename + "_10.csv")
df_MOW_MUN2425_11 = pd.read_csv(raw_data_dir + ARSO_dir + year2425_dir + MOW_MUN_filename + "_11.csv")

df_MOW_MUN2526_9 = pd.read_csv(raw_data_dir + ARSO_dir + year2526_dir + MOW_MUN_filename + "_9.csv")
df_MOW_MUN2526_10 = pd.read_csv(raw_data_dir + ARSO_dir + year2526_dir + MOW_MUN_filename + "_10.csv")
df_MOW_MUN2526_11 = pd.read_csv(raw_data_dir + ARSO_dir + year2526_dir + MOW_MUN_filename + "_11.csv")

MOW_REG_filename = "MOW_REG.csv"

# df_MOW_REG2425 = pd.read_csv(raw_data_dir + ARSO_dir + year2425_dir + MOW_REG_filename)
df_MOW_REG2526 = pd.read_csv(raw_data_dir + ARSO_dir + year2526_dir + MOW_REG_filename)

REG_filename = "REG.csv"

df_reg2425 = pd.read_csv(raw_data_dir + ARSO_dir + year2425_dir + REG_filename)
df_reg2526 = pd.read_csv(raw_data_dir + ARSO_dir + year2526_dir + REG_filename)

FINAL_filename = "FIN.csv"

df_fin2425 = pd.read_csv(raw_data_dir + ARSO_dir + year2425_dir + FINAL_filename)
df_fin2526 = pd.read_csv(raw_data_dir + ARSO_dir + year2526_dir + FINAL_filename)

vuz_akadem_dir = "VuzAkadem/"
vuz_akadem_filename = "vuz_akadem.csv"

df_vuz_akadem2526 = pd.read_csv(raw_data_dir + vuz_akadem_dir + year2526_dir + vuz_akadem_filename)

## Бельчонок

**Колонки:**
1. name - имя
2. total - баллы
3. result:
    - 0 - участник
    - 1 - пип 3 степень
    - 2 - пип 2 степень
    - 3 - пип 1 степень
4. (*year*) - год проведения

**Замечания:**
- есть один пропуск в баллах

**Предобработка**
1. Добавление колонки *year*
2. Конкатенация

In [593]:
df_belchonok2526.head()

               name  total  result
0  Сибагатуллина Н.   94.0       3
1         Акимов А.   66.0       3
2        Данилов А.   62.0       3
3         Петров Я.   62.0       3
4         Глебов М.   60.0       3

In [594]:
df_belchonok2526['result'].value_counts()

result
1    202
2    130
3    115
0      1
Name: count, dtype: int64

In [595]:
df_belchonok2425['result'].value_counts()

result
1    170
3     98
2     95
Name: count, dtype: int64

In [596]:
df_belchonok2526.shape

(448, 3)

In [597]:
df_belchonok2526.isna().sum()

name      1
total     1
result    0
dtype: int64

In [598]:
df_belchonok2425.isna().sum()

name      0
total     0
result    0
dtype: int64

### Bit of preparing

In [599]:
df_belchonok2425 = pd.read_csv(raw_data_dir + belchonok_dir + year2425_dir + belchonok_filename)
df_belchonok2526 = pd.read_csv(raw_data_dir + belchonok_dir + year2526_dir + belchonok_filename)

df_belchonok2425['year'] = '24-25'
df_belchonok2526['year'] = '25-26'

df_belchonok = pd.concat([df_belchonok2425, df_belchonok2526])
df_belchonok.head()

            name  total  result   year
0  Хакимзянов И.   51.0       3  24-25
1  Хмелевский М.   48.0       3  24-25
2     Еникеев К.   45.0       3  24-25
3  Главатских В.   41.0       3  24-25
4    Савицкая Т.   40.0       3  24-25

In [600]:
df_belchonok.to_csv(preprocessed_data_dir + "belchonok.csv", index=False)

---

## Шаг в будущее

**Колонки:**
1. surname - фамилия
2. name - имя
3. father_name - отчество
4. title:
    - 1 - призер
    - 2 - побед
5. (*grade*) - класс
6. (*place*) - место в зачете

**Предварительная обработка:**
1. Добавление колонок *grade*, *place*
2. Конкатенация

**Замечания**
- Один пропуск в отчестве

In [601]:
df_future2526_9.head()

      id      surname       name    father_name  title
0  65331      Альперт    Владияр      Андреевич      1
1  61520       Багров      Данил      Сергеевич      1
2  71206     Бацарова  Елизавета      Денисовна      1
3  48768  Белослудцев      Артём     Евгеньевич      1
4  63654    Замотохин       Глеб  Александрович      1

In [602]:
df_future2526_10.head()

      id    surname       name    father_name  title
0  68597     Анищук   Всеволод       Иванович      1
1  56287     Ботвин  Александр      Сергеевич      1
2  66747     Брылин     Михаил       Иванович      1
3  63730     Бубнов  Александр  Александрович      1
4  63548  Васильева      Мария        Юрьевна      1

In [603]:
df_future2526_11.head()

      id         surname       name    father_name  title
0  35616          Анохин       Глеб     Алексеевич      1
1  33114         Аргунов       Иван  Александрович      1
2  57954         Булахов  Владислав  Александрович      1
3  49991       Валиуллин    Альберт     Рустемович      1
4  91868  Волкова-Медова  Анастасия      Денисовна      1

In [604]:
df_future2526_9['title'].value_counts()

title
2    24
1    11
Name: count, dtype: int64

In [605]:
df_future2526_10['title'].value_counts()

title
2    31
1    15
Name: count, dtype: int64

In [606]:
df_future2526_11['title'].value_counts()

title
2    67
1    28
Name: count, dtype: int64

### Bit of preparing

In [607]:
df_future2526_9 = pd.read_csv(raw_data_dir + future_dir + year2526_dir + future_filename + "_9.csv")
df_future2526_10 = pd.read_csv(raw_data_dir + future_dir + year2526_dir + future_filename + "_10.csv")
df_future2526_11 = pd.read_csv(raw_data_dir + future_dir + year2526_dir + future_filename + "_11.csv")

df_future2526_9['grade'] = 9
df_future2526_10['grade'] = 10
df_future2526_11['grade'] = 11

df_future2526_9 = df_future2526_9.reset_index().rename(columns={'index': 'place'})
df_future2526_10 = df_future2526_10.reset_index().rename(columns={'index': 'place'})
df_future2526_11 = df_future2526_11.reset_index().rename(columns={'index': 'place'})

df_future = pd.concat([df_future2526_9, df_future2526_10, df_future2526_11])
df_future = df_future.sort_values(by=['grade', 'place'], ascending=[False, True])
df_future.head()

   place     id         surname       name    father_name  title  grade
0      0  35616          Анохин       Глеб     Алексеевич      1     11
1      1  33114         Аргунов       Иван  Александрович      1     11
2      2  57954         Булахов  Владислав  Александрович      1     11
3      3  49991       Валиуллин    Альберт     Рустемович      1     11
4      4  91868  Волкова-Медова  Анастасия      Денисовна      1     11

In [608]:
df_future.isna().sum()

place          0
id             0
surname        0
name           0
father_name    1
title          0
grade          0
dtype: int64

In [609]:
df_future.to_csv(preprocessed_data_dir + 'future.csv', index=False)

---

## Гранит науки

**Колонки**
1. reg - регион
2. name - Фамилия И. О.
3. grade - класс
4. total - баллы
5. result:
    - 3 - пип 1 степень
    - 2 - пип 2 степень
    - 1 - пип 3 степень
    - 0 - участник

**Предварительная обработка**
1. Заполнение пропусков в имени на NO_NAME

**Замечания**
- колонка имя формата фамилия И. О.

In [610]:
df_granit_nauki2526.head()

                     reg           name grade total  result
0      Самарская область     Федотов М.    10  91,5       3
1     Московская область      Брылин М.    10    87       3
2    Воронежская область      Бубнов К.    10    78       2
3        Санкт-Петербург  Обиджанова А.    10    76       2
4  Новосибирская область     Лысаков Р.    10    76       2

In [611]:
df_granit_nauki2526['result'].value_counts()

result
0    603
1     85
2     31
3      7
Name: count, dtype: int64

In [612]:
df_granit_nauki2526.isna().sum()

reg       0
name      0
grade     0
total     0
result    0
dtype: int64

### Bit of preparing

In [613]:
df_granit_nauki2526['name'] = df_granit_nauki2526['name'].fillna("NO_NAME")

df_granit_nauki2526.head()

                     reg           name grade total  result
0      Самарская область     Федотов М.    10  91,5       3
1     Московская область      Брылин М.    10    87       3
2    Воронежская область      Бубнов К.    10    78       2
3        Санкт-Петербург  Обиджанова А.    10    76       2
4  Новосибирская область     Лысаков Р.    10    76       2

In [614]:
df_granit_nauki2526.to_csv(preprocessed_data_dir + 'granit_nauki.csv', index=False)

---

## Innopolis

**Колонки**
1. name - фамилия имя
2. reg - регион
3. total - баллы
4. grade - класс
5. (*stage*) - этап

**Предварительная обработка**
1. Добавление колонки *stage*
2. Конкатенация
3. Заполнение пропусков в именях на NO_NAME

**Замечание**
- есть пропуски в имени
- есть пропуски в регионе
- есть пропуски в классе

In [615]:
df_innopolis2425_1.head()

             name  total  grade
0      Звездин В.    415    9.0
1  Сокольников А.    400   11.0
2     Тимофеев В.    375   10.0
3     Дьяконов С.    372   10.0
4    Валиуллин Д.    370   11.0

In [616]:
df_innopolis2526_1.head()

          name    A    B    C   D    E    F   result  grade
0   Коробко А.  100  100  100  85  100  485  Invited     11
1     Алоян Э.  100  100  100  76  100  476  Invited      9
2  Коновнин Л.  100  100  100  76  100  476  Invited     11
3  Халтурин А.  100  100  100  76  100  476  Invited     10
4  Карташов В.  100  100  100  49  100  449  Invited     10

In [617]:
df_innopolis2425_2.head()

             name  total  grade
0        Gatev A.  500.0    NaN
1       Кардаш К.  500.0    9.0
2  Зедгенизова М.  481.0   11.0
3   Фортунатов В.  432.0   11.0
4     Алексеев Д.  427.0   11.0

In [618]:
df_innopolis2526_2.head()

             name    A    B    C   D    E    F   result  grade
0       Машира Д.  100  100  100  46  100  446  Invited     10
1   Правосудов Д.  100  100  100  80   39  419  Invited      9
2      Альмиев К.  100  100  100   .  100  400  Invited     11
3  Миннахметов И.  100   60  100  33  100  393  Invited     11
4      Звездин В.  100    0  100  80  100  380  Invited      9

In [619]:
df_innopolis2425_3.head()

          name  total  grade              reg
0   Звездин В.    500     10  Санкт-Петербург
1    Кардаш К.    500      9           Гомель
2  Савицкий Е.    465     11      Светлогорск
3    Свирид Е.    448     11           Москва
4   Ходыкин Т.    432     11  Санкт-Петербург

In [620]:
df_innopolis2526_3.head()

            name    A    B    C    D    E   F  total  result  grade
0     Звездин В.  100  100  100  100  100  19    519     1.0     11
1      Кардаш К.  100  100  100  100  100  19    519     1.0     10
2   Кондрашин В.  100  100  100  100  100  19    519     1.0     10
3  Насыбуллин И.  100  100  100  100  100  19    519     1.0     10
4   Устименко А.  100  100  100  100  100  19    519     1.0     11

In [621]:
df_innopolis2425_1.isna().sum()

name     0
total    0
grade    5
dtype: int64

In [622]:
df_innopolis2425_2.isna().sum()

name       2
total      2
grade    530
dtype: int64

In [623]:
df_innopolis2425_3.isna().sum()

name     0
total    0
grade    0
reg      0
dtype: int64

In [624]:
df_innopolis2526_1.isna().sum()

name        0
A           0
B           0
C           0
D           0
E           0
F           0
result    560
grade       0
dtype: int64

In [625]:
df_innopolis2526_1['result'].value_counts()

result
Invited    180
Reserve     62
Name: count, dtype: int64

In [626]:
df_innopolis2526_2.isna().sum()

name        0
A           0
B           0
C           0
D           0
E           0
F           0
result    649
grade       0
dtype: int64

In [627]:
df_innopolis2526_3.dtypes

name       object
A          object
B          object
C          object
D          object
E          object
F          object
total       int64
result    float64
grade       int64
dtype: object

In [628]:
df_innopolis2526_3.isna().sum()

name        0
A           0
B           0
C           0
D           0
E           0
F           0
total       0
result    196
grade       0
dtype: int64

### Bit of preparing

In [629]:
df_innopolis2425_1 = pd.read_csv(raw_data_dir + innopolis_dir + year2425_dir + innopolis_filename + "_1.csv")
df_innopolis2425_2 = pd.read_csv(raw_data_dir + innopolis_dir + year2425_dir + innopolis_filename + "_2.csv")
df_innopolis2425_3 = pd.read_csv(raw_data_dir + innopolis_dir + year2425_dir + innopolis_filename + "_3.csv")

df_innopolis2526_1 = pd.read_csv(raw_data_dir + innopolis_dir + year2526_dir + innopolis_filename + "_1.csv")
df_innopolis2526_2 = pd.read_csv(raw_data_dir + innopolis_dir + year2526_dir + innopolis_filename + "_2.csv")
df_innopolis2526_3 = pd.read_csv(raw_data_dir + innopolis_dir + year2526_dir + innopolis_filename + "_3.csv")

df_innopolis2425_1['stage'] = 1
df_innopolis2425_2['stage'] = 2
df_innopolis2425_3['stage'] = 3

df_innopolis2526_1['stage'] = 1
df_innopolis2526_2['stage'] = 2
df_innopolis2526_3['stage'] = 3

df_innopolis2425 = pd.concat([df_innopolis2425_1, df_innopolis2425_2, df_innopolis2425_3])
df_innopolis2526 = pd.concat([df_innopolis2526_1, df_innopolis2526_2, df_innopolis2526_3])

df_innopolis2425['year'] = '24-25'
df_innopolis2425['name'] = df_innopolis2425['name'].fillna("NO_NAME")
df_innopolis2425 = df_innopolis2425.sort_values(['stage', 'grade', 'total'], ascending=[True, False, False])

df_innopolis2526['year'] = '25-26'
df_innopolis2526['name'] = df_innopolis2526['name'].fillna("NO_NAME")
df_innopolis2526 = df_innopolis2526.sort_values(['stage', 'grade', 'total'], ascending=[True, False, False])

df_innopolis = pd.concat([df_innopolis2425, df_innopolis2526])

task_labmda = lambda x: 0 if x == '.' else float(x)

df_innopolis['A'] = df_innopolis['A'].fillna(0).apply(task_labmda)
df_innopolis['B'] = df_innopolis['B'].fillna(0).apply(task_labmda)
df_innopolis['C'] = df_innopolis['C'].fillna(0).apply(task_labmda)
df_innopolis['D'] = df_innopolis['D'].fillna(0).apply(task_labmda)
df_innopolis['E'] = df_innopolis['E'].fillna(0).apply(task_labmda)
df_innopolis['F'] = df_innopolis['F'].fillna(0).apply(task_labmda)

def get_total(x):
    if x['total'] == np.nan:
        return x['total']
    else:
        return x['A'] + x['B'] + x['C'] + x['D'] + x['E'] + x['F']

df_innopolis['total'] = df_innopolis.apply(get_total, axis=1)

df_innopolis['result'] = df_innopolis['result'].fillna("Deny")

df_innopolis = df_innopolis.sort_values(['year', 'stage', 'grade', 'total'], ascending=[False, True, False, False])

df_innopolis.head()

,name,total,grade,stage,reg,year,A,B,C,D,E,F,result
92,Abdulrahman A.,684.0,12.0,1,NaN,25-26,100.0,100.0,100.0,42.0,0.0,342.0,Invited
143,Adeeb O.,600.0,12.0,1,NaN,25-26,100.0,100.0,100.0,0.0,0.0,300.0,Invited
282,Judy W.,404.0,12.0,1,NaN,25-26,100.0,0.0,60.0,42.0,0.0,202.0,Deny
372,Laure H.,344.0,12.0,1,NaN,25-26,100.0,30.0,0.0,42.0,0.0,172.0,Deny
384,Abdalaziz M.,340.0,12.0,1,NaN,25-26,100.0,50.0,20.0,0.0,0.0,170.0,Deny

In [630]:
df_innopolis2526['grade'].value_counts()

grade
11    844
10    551
9     281
8     121
7      59
12     15
6       5
Name: count, dtype: int64

In [631]:
df_innopolis2526.isna().sum()

name         0
A            0
B            0
C            0
D            0
E            0
F            0
result    1405
grade        0
stage        0
total     1616
year         0
dtype: int64

In [632]:
df_innopolis.to_csv(preprocessed_data_dir + 'innopolis.csv', index=False)

---

## ITMO

**Колонки**
1. name - Фамилия Имя Отчество
2. reg - регион
3. result:
    - 3 - пип 1 степень
    - 2 - пип 2 степень
    - 1 - пип 3 степень
    - 0 - участник

In [633]:
df_itmo2425.head()

          name                   reg  result  grade
0   Киселев А.     Орловская область       3      8
1  Богданов Н.  Свердловская область       3      8
2  Снохинов Г.   Саратовская область       3      8
3   Ганичев Ф.     Кировская область       2      8
4    Козлов Д.       Санкт-Петербург       2      8

In [634]:
df_itmo2526.head()

            name                    reg  result  grade
0  Сисьмекова З.   Свердловская область       3      8
1       Щукин Н.                 Москва       3      8
2    Зеленкин К.                 Москва       3      8
3     Бисярин А.        Санкт-Петербург       2      8
4     Русанов Н.  Новосибирская область       2      8

In [635]:
df_itmo2425['result'].value_counts()

result
1    60
2    51
3    43
0     1
Name: count, dtype: int64

In [636]:
df_itmo2526['result'].value_counts()

result
1    58
3    30
2    29
Name: count, dtype: int64

In [637]:
df_itmo2526.isna().sum()

name      0
reg       0
result    0
grade     0
dtype: int64

### Bit of preparing

In [638]:
df_itmo2425 = pd.read_csv(raw_data_dir + itmo_dir + year2425_dir + itmo_filename)
df_itmo2526 = pd.read_csv(raw_data_dir + itmo_dir + year2526_dir + itmo_filename)

df_itmo2425['year'] = '24-25'
df_itmo2526['year'] = '25-26'

df_itmo = pd.concat([df_itmo2425, df_itmo2526], axis=0)

df_itmo.head()

          name                   reg  result  grade   year
0   Киселев А.     Орловская область       3      8  24-25
1  Богданов Н.  Свердловская область       3      8  24-25
2  Снохинов Г.   Саратовская область       3      8  24-25
3   Ганичев Ф.     Кировская область       2      8  24-25
4    Козлов Д.       Санкт-Петербург       2      8  24-25

In [639]:
df_itmo.to_csv(preprocessed_data_dir + 'itmo.csv', index=False)

---

## MOSH

**Колонки**
1. surname - Фамилия
2. first_initial - первая буква имени
3. second_initial - первая буква отчества
4. class_study - класс
5. region - код региона
6. score - баллы
7. title:
    - победитель
    - призер2степени
    - призер3степени

In [640]:
df_MOSH2526.head()

,id,surname,first_inital,second_initial,class_study,class_partake,region,score,title
0,41376161,Островский,А,В,11,11,77,433.06,победитель
1,41376047,Ивлеев,М,С,10,11,77,371.52,победитель
2,41376080,Карпиков,Н,В,10,11,77,344.40,победитель
3,41376182,Горелов,Г,А,10,11,77,299.54,победитель
4,41376153,Девятов,С,А,10,11,77,283.99,победитель

In [641]:
df_MOSH2526['title'].value_counts()

title
призёр3степени    160
призёр2степени     91
победитель         79
Name: count, dtype: int64

In [642]:
df_MOSH2526.isna().sum()

id                0
surname           0
first_inital      0
second_initial    0
class_study       0
class_partake     0
region            0
score             0
title             0
dtype: int64

### Bit of preparing

In [643]:
df_MOSH2526.to_csv(preprocessed_data_dir + 'mosh.csv', index=False)

---

## Открытая олимпиада школьников

**КОЛОНКИ**
1. name - Фамилия И.
2. grade - класс
3. participation_grade - класс участия
4. reg - регион
5. A1, B1, C1, D1, A2, B2, C2, D2 - баллы по задачам
6. total - сумма балов
7. result:
    - 3 - пип 1 степень
    - 2 - пип 2 степень
    - 1 - пип 3 степень
    - 0 - участник
8. (*year*) - год проведения

**ПРЕДОБРАБОТКА**
1. Добавление колонки *year*
2. Конкатенация

In [644]:
df_open2425.head()

,name,grade,participation_grade,reg,A1,B1,C1,D1,A2,B2,C2,D2,total,result
0,Лосев П.,11,11,Москва,83.0,100.0,100.0,100.0,78.0,100.0,100.0,100.0,761,3
1,Абдуллин Г.,11,11,Казань,100.0,100.0,100.0,100.0,45.0,100.0,100.0,46.0,691,3
2,Звездин В.,10,11,Санкт-Петербург,83.0,100.0,100.0,100.0,45.0,100.0,100.0,52.0,680,3
3,Грекова Д.,11,11,Москва,93.0,72.0,100.0,100.0,45.0,100.0,100.0,22.0,632,3
4,Цыбань Л.,10,11,Москва,36.0,62.0,100.0,100.0,32.0,100.0,100.0,100.0,630,3

In [645]:
df_open2526.head()

,name,grade,participation_grade,reg,A1,B1,C1,D1,A2,B2,C2,D2,total,result
0,Кузнецов И.,11,11,Санкт-Петербург,30.0,100.0,100.0,100.0,95.0,100.0,100.0,100.0,725,3
1,Звездин В.,11,11,Санкт-петербург,30.0,100.0,100.0,100.0,84.0,100.0,100.0,100.0,714,3
2,Муханов С.,11,11,Москва,30.0,100.0,82.0,100.0,91.0,100.0,100.0,100.0,703,3
3,Кардаш К.,10,11,Гомель,30.0,100.0,100.0,100.0,68.0,100.0,100.0,100.0,698,3
4,Жиганов В.,11,11,Москва,30.0,100.0,100.0,100.0,98.0,100.0,100.0,50.0,678,3

In [646]:
df_open2526.isna().sum()

name                     0
grade                    0
participation_grade      0
reg                      0
A1                      33
B1                       1
C1                     116
D1                     101
A2                     237
B2                      59
C2                      32
D2                      24
total                    0
result                   0
dtype: int64

In [647]:
df_open2425.isna().sum()

name                     0
grade                    0
participation_grade      0
reg                      0
A1                     191
B1                      14
C1                      41
D1                       8
A2                      91
B2                      31
C2                      59
D2                     141
total                    0
result                   0
dtype: int64

In [648]:
df_open2425['result'].value_counts()

result
0    308
1     45
2     38
3     38
Name: count, dtype: int64

### Bit of preparing

In [649]:
df_open2425 = pd.read_csv(raw_data_dir + open_dir + year2425_dir + open_filename)
df_open2526 = pd.read_csv(raw_data_dir + open_dir + year2526_dir + open_filename)

df_open2425['year'] = '24-25'
df_open2526['year'] = '25-26'

df_open = pd.concat([df_open2425, df_open2526])
df_open.head()

,name,grade,participation_grade,reg,A1,B1,C1,D1,A2,B2,C2,D2,total,result,year
0,Лосев П.,11,11,Москва,83.0,100.0,100.0,100.0,78.0,100.0,100.0,100.0,761,3,24-25
1,Абдуллин Г.,11,11,Казань,100.0,100.0,100.0,100.0,45.0,100.0,100.0,46.0,691,3,24-25
2,Звездин В.,10,11,Санкт-Петербург,83.0,100.0,100.0,100.0,45.0,100.0,100.0,52.0,680,3,24-25
3,Грекова Д.,11,11,Москва,93.0,72.0,100.0,100.0,45.0,100.0,100.0,22.0,632,3,24-25
4,Цыбань Л.,10,11,Москва,36.0,62.0,100.0,100.0,32.0,100.0,100.0,100.0,630,3,24-25

In [650]:
df_open.isna().sum()

name                     0
grade                    0
participation_grade      0
reg                      0
A1                     224
B1                      15
C1                     157
D1                     109
A2                     328
B2                      90
C2                      91
D2                     165
total                    0
result                   0
year                     0
dtype: int64

In [651]:
df_open.to_csv(preprocessed_data_dir + 'open.csv', index=False)

---

## ВСОШ: школьный этап | Москва

**Колонки**
1. surname - Фамилия
2. first_initial - Первая буква имени
3. second_initial - Первая буква отчества
4. class_partake - класс участия
5. class_study - класс обучекния
6. score - баллы
7. title:
    - победитель
    - призер
    - участник

**Предобработка**
1. Конкатенация

**Замечания**
1. Пропуски в букве отчества

In [652]:
df_MOW_SCH2425_9.head()

,id,surname,first_inital,second_initial,class_study,class_partake,score,title
0,vGhxXZJg,Агапченко,Н,Н,9,9,500,победитель
1,VGVRxYwF,Андреев,С,Р,9,9,500,победитель
2,mdgnfJln,Артемьев,М,М,9,9,500,победитель
3,05Bvemyv,Артимович,К,О,9,9,500,победитель
4,GjZUE4Nf,Артюхов,Э,А,9,9,500,победитель

In [653]:
df_MOW_SCH2526_9.head()

,id,surname,first_inital,second_initial,class_study,class_partake,region,score,title
0,325849054,Абубакиров,Д,Д,9,9,77,500.0,победитель
1,325849050,Богдановский,М,С,9,9,77,500.0,победитель
2,325832300,Горбачев,А,А,9,9,77,500.0,победитель
3,325847084,Дамбаев,Д,Ж,9,9,77,500.0,победитель
4,325850582,Дементьев,Г,А,9,9,77,500.0,победитель

In [654]:
df_MOW_MUN2526_10.head()

,id,surname,first_inital,second_initial,class_study,class_partake,region,score,title
0,41197363,Артемьев,М,М,10,10,77,500.0,победитель
1,41196929,Васильев,О,И,10,10,77,500.0,победитель
2,41197075,Волынец,П,Р,10,10,77,500.0,победитель
3,41197141,Вяргизова,А,Д,10,10,77,500.0,победитель
4,41197220,Горелов,Г,А,10,10,77,500.0,победитель

In [655]:
df_MOW_SCH2526_11.head()

,id,surname,first_inital,second_initial,class_study,class_partake,region,score,title
0,325828830,Александров,Н,А,11,11,77,500.0,победитель
1,325848986,Аргунов,И,А,11,11,77,500.0,победитель
2,325826133,Артюхов,И,С,11,11,77,500.0,победитель
3,325826406,Бейлезон,К,А,11,11,77,500.0,победитель
4,325845538,Бичоева,А,А,11,11,77,500.0,победитель

In [656]:
df_MOW_MUN2526_10.head()

,id,surname,first_inital,second_initial,class_study,class_partake,region,score,title
0,41197363,Артемьев,М,М,10,10,77,500.0,победитель
1,41196929,Васильев,О,И,10,10,77,500.0,победитель
2,41197075,Волынец,П,Р,10,10,77,500.0,победитель
3,41197141,Вяргизова,А,Д,10,10,77,500.0,победитель
4,41197220,Горелов,Г,А,10,10,77,500.0,победитель

In [657]:
df_MOW_MUN2526_10['title'].value_counts()

title
участник      672
призер        193
победитель     66
Name: count, dtype: int64

### Bit of preparing

In [658]:
df_MOW_SCH2425_9 = pd.read_csv(raw_data_dir + ARSO_dir + year2425_dir + MOW_SCH_filename + "_9.csv")
df_MOW_SCH2425_10 = pd.read_csv(raw_data_dir + ARSO_dir + year2425_dir + MOW_SCH_filename + "_10.csv")
df_MOW_SCH2425_11 = pd.read_csv(raw_data_dir + ARSO_dir + year2425_dir + MOW_SCH_filename + "_11.csv")
df_MOW_SCH2526_9 = pd.read_csv(raw_data_dir + ARSO_dir + year2526_dir + MOW_SCH_filename + "_9.csv")
df_MOW_SCH2526_10 = pd.read_csv(raw_data_dir + ARSO_dir + year2526_dir + MOW_SCH_filename + "_10.csv")
df_MOW_SCH2526_11 = pd.read_csv(raw_data_dir + ARSO_dir + year2526_dir + MOW_SCH_filename + "_11.csv")

df_MOW_SCH2425 = pd.concat([df_MOW_SCH2425_9, df_MOW_SCH2425_10, df_MOW_SCH2425_11])
df_MOW_SCH2425['year'] = "24-25"

df_MOW_SCH2526 = pd.concat([df_MOW_SCH2526_9, df_MOW_SCH2526_10, df_MOW_SCH2526_11])
df_MOW_SCH2526['year'] = "25-26"

df_MOW_SCH = pd.concat([df_MOW_SCH2425, df_MOW_SCH2526])

df_MOW_SCH.head()

,id,surname,first_inital,second_initial,class_study,class_partake,score,title,year,region
0,vGhxXZJg,Агапченко,Н,Н,9,9,500.0,победитель,24-25,NaN
1,VGVRxYwF,Андреев,С,Р,9,9,500.0,победитель,24-25,NaN
2,mdgnfJln,Артемьев,М,М,9,9,500.0,победитель,24-25,NaN
3,05Bvemyv,Артимович,К,О,9,9,500.0,победитель,24-25,NaN
4,GjZUE4Nf,Артюхов,Э,А,9,9,500.0,победитель,24-25,NaN

In [659]:
df_MOW_SCH.isna().sum()

id                    0
surname               0
first_inital          0
second_initial     1144
class_study           0
class_partake         0
score                 0
title                 0
year                  0
region            33100
dtype: int64

In [660]:
df_MOW_SCH.to_csv(preprocessed_data_dir + 'MOW_SCH.csv', index=False)

---

## ВСОШ: муниципальный этап | Москва

**Колонки**
1. surname - Фамилия
2. first_initial - Первая буква имени
3. second_initial - Первая буква отчества
4. class_partake - класс участия
5. class_study - класс обучекния
6. score - баллы
7. title:
    - победитель
    - призер
    - участник

**Предобработка**
1. Конкатенация

**Замечания**
1. Пропуски в букве отчества

In [661]:
df_MOW_MUN2425_9.head()

,id,surname,first_inital,second_initial,class_study,class_partake,region,score,title
0,39043018,Бабинцев,С,К,9,9,77,500.0,победитель
1,39043016,Гасаненко,А,А,8,9,77,500.0,победитель
2,39043019,Марченко,А,О,8,9,77,500.0,победитель
3,39043017,Пинский,А,Г,6,9,77,500.0,победитель
4,39043014,Приводнов,М,С,9,9,77,500.0,победитель

In [662]:
df_MOW_MUN2526_9.head()

,id,surname,first_inital,second_initial,class_study,class_partake,region,score,title
0,41196750,Богдановский,М,С,9,9,77,500.0,победитель
1,41195931,Гасаненко,А,А,9,9,77,500.0,победитель
2,41195776,Давыдов,П,Д,9,9,77,500.0,победитель
3,41195582,Дементьев,Г,А,9,9,77,500.0,победитель
4,41195713,Дьяконов,К,А,9,9,77,500.0,победитель

In [663]:
df_MOW_MUN2526_10.head()

,id,surname,first_inital,second_initial,class_study,class_partake,region,score,title
0,41197363,Артемьев,М,М,10,10,77,500.0,победитель
1,41196929,Васильев,О,И,10,10,77,500.0,победитель
2,41197075,Волынец,П,Р,10,10,77,500.0,победитель
3,41197141,Вяргизова,А,Д,10,10,77,500.0,победитель
4,41197220,Горелов,Г,А,10,10,77,500.0,победитель

In [664]:
df_MOW_MUN2526_11.head()

,id,surname,first_inital,second_initial,class_study,class_partake,region,score,title
0,41197798,Венгеров,В,Р,11,11,77,500.0,победитель
1,41197900,Голубов,Н,М,11,11,77,500.0,победитель
2,41197975,Иванов,П,И,11,11,77,500.0,победитель
3,41197971,Игнатов,Д,М,11,11,77,500.0,победитель
4,41197711,Касинов,В,С,11,11,77,500.0,победитель

### Bit of preparing

In [665]:
df_MOW_MUN2425_9 = pd.read_csv(raw_data_dir + ARSO_dir + year2425_dir + MOW_MUN_filename + "_9.csv")
df_MOW_MUN2425_10 = pd.read_csv(raw_data_dir + ARSO_dir + year2425_dir + MOW_MUN_filename + "_10.csv")
df_MOW_MUN2425_11 = pd.read_csv(raw_data_dir + ARSO_dir + year2425_dir + MOW_MUN_filename + "_11.csv")

df_MOW_MUN2526_9 = pd.read_csv(raw_data_dir + ARSO_dir + year2526_dir + MOW_MUN_filename + "_9.csv")
df_MOW_MUN2526_10 = pd.read_csv(raw_data_dir + ARSO_dir + year2526_dir + MOW_MUN_filename + "_10.csv")
df_MOW_MUN2526_11 = pd.read_csv(raw_data_dir + ARSO_dir + year2526_dir + MOW_MUN_filename + "_11.csv")


df_MOW_MUN2425 = pd.concat([df_MOW_MUN2425_9, df_MOW_MUN2425_10, df_MOW_MUN2425_11])
df_MOW_MUN2425['year'] = '24-25'

df_MOW_MUN2526 = pd.concat([df_MOW_MUN2526_9, df_MOW_MUN2526_10, df_MOW_MUN2526_11])
df_MOW_MUN2526['year'] = '25-26'

df_MOW_MUN = pd.concat([df_MOW_MUN2425, df_MOW_MUN2526])

df_MOW_MUN.head()

,id,surname,first_inital,second_initial,class_study,class_partake,region,score,title,year
0,39043018,Бабинцев,С,К,9,9,77,500.0,победитель,24-25
1,39043016,Гасаненко,А,А,8,9,77,500.0,победитель,24-25
2,39043019,Марченко,А,О,8,9,77,500.0,победитель,24-25
3,39043017,Пинский,А,Г,6,9,77,500.0,победитель,24-25
4,39043014,Приводнов,М,С,9,9,77,500.0,победитель,24-25

In [666]:
df_MOW_MUN.isna().sum()

id                 0
surname            0
first_inital       0
second_initial    20
class_study        0
class_partake      0
region             0
score              0
title              0
year               0
dtype: int64

In [667]:
df_MOW_MUN.to_csv(preprocessed_data_dir + "MOW_MUN.csv", index=False)

---

## ВСОШ: региональный этап | Москва

**Колонки**
1. surname - Фамилия
2. first_initial - Первая буква имени
3. second_initial - Первая буква отчества
4. class_partake - класс участия
5. class_study - класс обучекния
6. score - баллы
7. title:
    - победитель
    - призер
    - участник

**Замечания**
1. Пропуски в букве отчества
2. Пропуски в баллах

In [668]:
df_MOW_REG2526.head()

,id,surname,first_inital,second_initial,class_study,class_partake,region,score,title
0,41232839,Артюхов,И,С,11,11,77,NaN,победитель
1,41232893,Васильев,А,А,11,11,77,NaN,победитель
2,41232735,Данилов,Н,И,11,11,77,NaN,победитель
3,41232902,Дьяконов,С,А,11,11,77,NaN,победитель
4,41232856,Жиганов,В,А,11,11,77,NaN,победитель

In [669]:
df_MOW_REG2526.isna().sum()

id                  0
surname             0
first_inital        0
second_initial      3
class_study         0
class_partake       0
region              0
score             915
title               0
dtype: int64

### Bit of preparing

In [670]:
df_MOW_REG2526.to_csv(preprocessed_data_dir + "MOW_REG.csv", index=False)

---

## ВСОШ: региональный этап | Все

**Колонки**
1. Имя => name
2. Регион => region
3. Класс => grade
4. A1
5. B1
6. C1
7. D1
8. A2
9. B2
10. C2
11. D2
12. Sum

**Предварительная обработка**
1. Переименование колонок

**Замечания**
- пропуски в баллах по задачам

In [671]:
df_reg2425.head()

,Имя,Регион,Класс,A1,B1,C1,D1,A2,B2,C2,D2,Sum
0,Алексеев Иван Сергеевич,Санкт-Петербург,10,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0
1,Звездин Владимир Сергеевич,Санкт-Петербург,10,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0
2,Кузнецов Евгений Сергеевич,Липецкая область,9,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0
3,Часовских И. М.,Сириус,11,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0
4,Янковский Алексей Владимирович,Москва,9,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0

In [672]:
df_reg2526.head()

,Имя,Регион,Класс,A1,B1,C1,D1,A2,B2,C2,D2,Sum
0,Ашахмуров Артур Васильевич,Московская область,10,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0
1,Гриненко Артемий Андреевич,Москва,10,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0
2,Звездин Владимир Сергеевич,Санкт-Петербург,11,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0
3,Кравченко Максим Юрьевич,Москва,10,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0
4,Кузнецов Иван Александрович,Санкт-Петербург,11,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0

### Bit of preparing

In [673]:
df_reg2425 = df_reg2425.rename(columns={'Имя': 'name', 'Регион': 'region', 'Класс': 'grade'})
df_reg2526 = df_reg2526.rename(columns={'Имя': 'name', 'Регион': 'region', 'Класс': 'grade'})

df_reg2425['year'] = '24-25'
df_reg2526['year'] = '25-26'

df_reg = pd.concat([df_reg2425, df_reg2526])

df_reg.head()

,name,region,grade,A1,B1,C1,D1,A2,B2,C2,D2,Sum,year
0,Алексеев Иван Сергеевич,Санкт-Петербург,10,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0,24-25
1,Звездин Владимир Сергеевич,Санкт-Петербург,10,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0,24-25
2,Кузнецов Евгений Сергеевич,Липецкая область,9,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0,24-25
3,Часовских И. М.,Сириус,11,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0,24-25
4,Янковский Алексей Владимирович,Москва,9,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,800.0,24-25

In [674]:
df_reg.isna().sum()

name         0
region      10
grade        0
A1        1328
B1        2635
C1        6769
D1        8570
A2        1588
B2        3131
C2        5463
D2        9685
Sum          0
year         0
dtype: int64

In [675]:
df_reg.to_csv(preprocessed_data_dir + "reg.csv", index=False)

---

## Закл ВСОШ

In [676]:
df_fin2425.head()

,id,surname,name,father_name,class_study,region,score,title
0,1,Грекова,Дарья,Сергеевна,11,г. Москва,724,победитель
1,2,Абдуллин,Гимран,Маратович,11,Республика Татарстан,720,победитель
2,3,Жиганов,Владислав,Александрович,10,г. Москва,682,победитель
3,4,Звездин,Владимир,Сергеевич,10,г. Санкт-Петербург,676,победитель
4,5,Иванов,Нил,Алексеевич,11,г. Москва,668,победитель

In [677]:
df_fin2526.head()

,id,surname,name,father_name,region,class_study,p1,p2,p3,p4,p5,p6,p7,p8,score,title
0,1,Звездин,Владимир,Сергеевич,Санкт-Петербург,11,100,100,58,100,100,100,100,74,732,1.0
1,2,Кузнецов,Евгений,Сергеевич,Липецкая область,10,100,100,98,54,100,95,100,64,711,1.0
2,3,Приводнов,Марк,Сергеевич,Москва,10,100,100,95,58,100,100,77,80,710,1.0
3,4,Жиганов,Владислав,Александрович,Москва,11,100,100,90,64,100,100,59,67,680,1.0
4,5,Кравченко,Максим,Юрьевич,Москва,10,100,100,57,47,100,100,100,67,671,1.0

### Bit of preprocessing

In [678]:
df_fin2425 = pd.read_csv(raw_data_dir + ARSO_dir + year2425_dir + FINAL_filename)
df_fin2526 = pd.read_csv(raw_data_dir + ARSO_dir + year2526_dir + FINAL_filename)

df_fin2425['year'] = '24-25'
df_fin2526['year'] = '25-26'

df_fin = pd.concat([df_fin2425, df_fin2526])

df_fin.head()

,id,surname,name,father_name,class_study,region,score,title,year,p1,p2,p3,p4,p5,p6,p7,p8
0,1,Грекова,Дарья,Сергеевна,11,г. Москва,724,победитель,24-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Абдуллин,Гимран,Маратович,11,Республика Татарстан,720,победитель,24-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Жиганов,Владислав,Александрович,10,г. Москва,682,победитель,24-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Звездин,Владимир,Сергеевич,10,г. Санкт-Петербург,676,победитель,24-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Иванов,Нил,Алексеевич,11,г. Москва,668,победитель,24-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [679]:
df_fin.isna().sum()

id               0
surname          0
name             0
father_name      0
class_study      0
region           0
score            0
title          242
year             0
p1             225
p2             225
p3             225
p4             225
p5             225
p6             225
p7             225
p8             225
dtype: int64

In [680]:
df_fin.to_csv(preprocessed_data_dir + "fin.csv", index=False)

---

## Вузовская академическая олимпиада

**Колонки**
1. name - фамилия имя отчество
2. reg - регион
3. total - баллы
4. grade - класс

In [681]:
df_vuz_akadem2526.head()

            name                   reg  total  grade
0  Мухамадиев Д.  Республика Татарстан    604     10
1   Котлечков Е.  Свердловская область    594     11
2     Андреев А.    Ростовская область    585     11
3     Лободов М.         Пермский край    570     10
4   Кондрашин В.  Свердловская область    548     10

In [682]:
df_vuz_akadem2526.isna().sum()

name     0
reg      0
total    0
grade    0
dtype: int64

In [683]:
df_vuz_akadem2526.to_csv(preprocessed_data_dir + "vuz_akadem2526.csv", index=False)

---